### ISSUE TITLE
May I suggest adding full readme and renaming

### ISSUE THREAD

**Issue by shaneholloman** [ctf0/local-history#8]
While keeping your respectful attribution info:

- May I suggest adding full README.md and renaming the project??

**Comment by ctf0** [comment]
> adding full README.md

understandable & will do so soon

> renaming the project

whats the point ?

**Comment by shaneholloman** [comment]
> whats the point ?

just to separate this in the vs code marketplace 

You have made it better and seems like a good time to give it a unique name?

either way, good stuff, I use it all the time

**Comment by Cinabutts** [comment]
Didn't feel like creating a new issue for this but i had gone a month losing all backup ability because i didn't realize it'd just do NOTHING if you were to place a slash at the end of the absolute backup path ie in my case `C:\Users\Joeys-PC\Documents\GitHub\Windhawk\HistoryBACKUPS` (works) from `C:\Users\Joeys-PC\Documents\GitHub\Windhawk\HistoryBACKUPS\` (doesn't)

Would've been cool to have known this before hand lol
